"""isotope and biodi tables

Revision ID: 346232f8e1b1
Revises: 7a3ee3e6a3c0
Create Date: 2018-12-17 13:23:58.893210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346232f8e1b1'
down_revision = '7a3ee3e6a3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isotope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isotope_name', sa.String(length=32), nullable=True),
    sa.Column('half_life', sa.Float(precision=32), nullable=True),
    sa.Column('hidex_calfactor', sa.Float(precision=32), nullable=True),
    sa.Column('wizard_calfactor', sa.Float(precision=32), nullable=True),
    sa.Column('cal_factor_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isotope_cal_factor_date'), 'isotope', ['cal_factor_date'], unique=False)
    op.create_index(op.f('ix_isotope_isotope_name'), 'isotope', ['isotope_name'], unique=True)
    op.create_table('bio_di',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpm', sa.Integer(), nullable=True),
    sa.Column('isotope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isotope_id'], ['isotope.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bio_di')
    op.drop_index(op.f('ix_isotope_isotope_name'), table_name='isotope')
    op.drop_index(op.f('ix_isotope_cal_factor_date'), table_name='isotope')
    op.drop_table('isotope')
    # ### end Alembic commands ###
